### PR TITLE
modulesync 1.1.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by wyardley** [comment]
The only complaint is about Vagrantfile not being snake case. 
Would the right fix be to add `Vagrantfile` to the rubocop excludes in modulesync_config, or just to get rid of the Vagrantfile? There's no other acceptance test currently, afaict, but I'm guessing this is no longer used?

**Comment by bastelfreak** [comment]
Not sure if anybody uses the Vagrantfile, but we should exclude it in rubocop. I merged the related modulesync_config pr

**Comment by bastelfreak** [comment]
rebvased the branch to exclude Vagrantfile again

**Comment by rski** [comment]
(sorry clicked on a thing by mistake)

**Pull request merged**
